config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :offer_demands,       only: [:new, :create, :edit, :update, :destroy, :show]
  resources :comments,            only: [:create, :destroy]
  resources :dorms,               only: [:show]
end

app/models/offer_demand.rb
class OfferDemand < ActiveRecord::Base
  belongs_to :user
  belongs_to :type
  has_many :comments, dependent: :destroy
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 70 }
  validates :content, presence: true, length: { maximum: 200 }
  validates :price, presence: true, numericality: true
  validates :type_id, presence: true
  validate  :picture_size

  def self.per_page
    8
  end

  def start_time
    self.date
  end

  def self.my_search(search, page)
    if search.blank?
      paginate_by_sql(<<-SQL, page: page, per_page: per_page)
        SELECT od.*, round(cast(AVG(com.rating) as numeric),2) as rating,
             t.name as type_name, d.name as dorm_name, r.name as region_name
        FROM offer_demands od
        JOIN users u ON u.id = od.user_id
        JOIN dorms d ON u.dorm_id = d.id
        JOIN regions r ON d.regions_id = r.id
        JOIN types t ON t.id = od.type_id
        LEFT JOIN comments com ON com.offer_demand_id = od.id
        WHERE od.visible = true
        GROUP BY od.id, t.name, d.name, r.name
        ORDER BY od.title
      SQL
    else
      paginate_by_sql(<<-SQL, page: page, per_page: per_page)
        SELECT od.*, round(cast(AVG(com.rating) as numeric),2) as rating,
             t.name as type_name, d.name as dorm_name, r.name as region_name
        FROM offer_demands od
        JOIN users u ON u.id = od.user_id
        JOIN dorms d ON u.dorm_id = d.id
        JOIN regions r ON d.regions_id = r.id
        JOIN types t ON t.id = od.type_id
        LEFT JOIN comments com ON com.offer_demand_id = od.id
        WHERE od.visible = true
        AND (to_tsvector('simple', od.title) @@ plainto_tsquery('simple', #{ActiveRecord::Base.sanitize(search)})
        OR to_tsvector('simple', od.content) @@ plainto_tsquery('simple', #{ActiveRecord::Base.sanitize(search)}))
        GROUP BY od.id, t.name, d.name, r.name
        ORDER BY od.title
      SQL
    end
  end

  def self.my_search_in_concrete_dorm(search, id)
    if search.blank?
      find_by_sql <<-SQL
        SELECT od.*, round(cast(AVG(com.rating) as numeric),2) as rating,
             t.name as type_name, d.name as dorm_name, r.name as region_name
        FROM dorms d
        JOIN regions r ON d.regions_id = r.id
        JOIN users u on u.dorm_id = d.id
        JOIN offer_demands od ON od.user_id = u.id
        JOIN types t ON t.id = od.type_id
        LEFT JOIN comments com ON com.offer_demand_id = od.id
        WHERE od.visible = true AND d.id = #{ActiveRecord::Base.sanitize(id)}
        GROUP BY od.id, t.name, d.name, r.name
        ORDER BY od.title
      SQL
    else
      find_by_sql <<-SQL
        SELECT od.*, round(cast(AVG(com.rating) as numeric),2) as rating,
             t.name as type_name, d.name as dorm_name, r.name as region_name
        FROM dorms d
        JOIN regions r ON d.regions_id = r.id
        JOIN users u on u.dorm_id = d.id
        JOIN offer_demands od ON od.user_id = u.id
        JOIN types t ON t.id = od.type_id
        LEFT JOIN comments com ON com.offer_demand_id = od.id
        WHERE od.visible = true AND d.id = #{ActiveRecord::Base.sanitize(id)}
        AND (to_tsvector('simple', od.title) @@ plainto_tsquery('simple', #{ActiveRecord::Base.sanitize(search)})
        OR to_tsvector('simple', od.content) @@ plainto_tsquery('simple', #{ActiveRecord::Base.sanitize(search)}))
        GROUP BY od.id, t.name, d.name, r.name
        ORDER BY od.title
      SQL
    end
  end

  def self.my_all_offers_by_user(id, page)
    my_sql = <<-SQL
      SELECT od.*, round(cast(AVG(com.rating) as numeric),2) as rating,
             t.name as type_name
      FROM offer_demands od
      LEFT JOIN comments com ON com.offer_demand_id = od.id
      JOIN types t ON t.id = od.type_id
      WHERE od.user_id = #{ActiveRecord::Base.sanitize(id)}
      GROUP BY od.id, t.name
      ORDER BY od.title
    SQL
    paginate_by_sql(my_sql, page: page, per_page: per_page)
  end

  def self.my_count_offers_by_user(user)
    my_sql = <<-SQL
      SELECT count(od.id)
      FROM offer_demands od
      JOIN users u ON u.id = od.user_id
      WHERE u.id = #{ActiveRecord::Base.sanitize(user.id)}
    SQL
    count_by_sql(my_sql)
  end

  def self.my_concrete_offer(id)
    my_sql = <<-SQL
      SELECT od.*, round(cast(AVG(com.rating) as numeric),2) as rating,
             t.name as type_name, d.name as dorm_name, r.name as region_name
      FROM offer_demands od
      JOIN types t ON t.id = od.type_id
      JOIN users u ON u.id = od.user_id
      JOIN dorms d ON u.dorm_id = d.id
      JOIN regions r ON d.regions_id = r.id
      LEFT JOIN comments com ON com.offer_demand_id = od.id
      WHERE od.id = #{ActiveRecord::Base.sanitize(id)}
      GROUP BY od.id, t.name, d.name, r.name
    SQL
    find_by_sql(my_sql)[0]
  end

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, 'should be less than 5MB')
      end
    end
end

app/controllers/offer_demands_controller.rb
class OfferDemandsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :visible_for_user, only: :show

  def show
    @comments = @offer_demand.comments.paginate(page: params[:page])
    @comment = current_user.comments.build if logged_in?
  end

  def new
    @offer_demand = OfferDemand.new
  end

  def create
    @offer_demand = current_user.offer_demands.new(offer_params)
    if @offer_demand.save
      flash[:success] = 'Nová ponuka vytvorená!'
      redirect_to @offer_demand
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @offer_demand.update_attributes(offer_params)
      flash[:success] = 'Ponuka upravená'
      redirect_to @offer_demand
    else
      render 'edit'
    end
  end

  def destroy
    OfferDemand.find(params[:id]).destroy
    flash[:success] = 'Ponuka zmazaná'
    redirect_to current_user
  end

  private

    def offer_params
      params.require(:offer_demand).permit(:title, :content, :price, :date, :picture, :type_id, :visible)
    end

    def correct_user
      @offer_demand = OfferDemand.find(params[:id])
      redirect_to(root_url) unless @offer_demand.user == current_user
    end

    def visible_for_user
      @offer_demand = OfferDemand.my_concrete_offer(params[:id])
      redirect_to(root_url) unless @offer_demand.user == current_user || @offer_demand.visible == true
    end
end

app/helpers/offer_demands_helper.rb
module OfferDemandsHelper

  def price_format(price)
    if price == 0
      'Zadarmo'
    else
      "#{price} €"
    end
  end

  def rating_format(avg)
    if avg.nil?
      '0.0'
    else
      "#{avg}"
    end
  end

end

app/views/offer_demands/_offer_demand.html.erb
<% if offer_demand.user == current_user || offer_demand.visible == true %>
<tr id="offer-<%= offer_demand.id %>" class="offer">
  <td>
    <div class="center">
      <% if offer_demand.picture? %>
          <%= link_to image_tag(offer_demand.picture.url, alt: 'Offer picture', class: 'picture-small'), offer_demand %>
      <% else %>
          <% case offer_demand.type_id %>
          <% when 1 %>
              <%= link_to image_tag('offer.png', alt: 'offer logo', class: 'picture-small'), offer_demand %>
          <% when 2 %>
              <%= link_to image_tag('service.png', alt: 'service logo', class: 'picture-small'), offer_demand %>
          <% when 3 %>
              <%= link_to image_tag('demand.png', alt: 'demand logo', class: 'picture-small'), offer_demand %>
          <% when 4 %>
              <%= link_to image_tag('event.png', alt: 'event logo', class: 'picture-small'), offer_demand %>
          <% when 5 %>
              <%= link_to image_tag('other.png', alt: 'other logo', class: 'picture-small'), offer_demand %>
          <% end %>
      <% end %>
    </div>
  </td>
  <td>
    <div>
      <div class="pull-right">
        <% unless offer_demand.date.nil? %>
            <div class="date">
              <%= offer_demand.date.strftime('%-d.%-m %Y') %>
            </div>
        <% end %>
        <% if offer_demand.respond_to?(:dorm_name) %>
          <div class="dorm">
            <%= offer_demand.dorm_name %>
          </div>
        <% end %>
        <% if offer_demand.respond_to?(:region_name) %>
          <div class="region">
            <%= offer_demand.region_name %>
          </div>
        <% end %>
      </div>
      <h4 class="title">
        <%= link_to offer_demand.title, offer_demand %>
      </h4>
      <p>
        <%= offer_demand.content[0..40] %><% if offer_demand.content.length > 41 %>...<% end %>
      </p>
      <p>
        <%= offer_demand.type_name %>
      </p>
    </div>
    <div>
      <% if current_user?User.find(offer_demand.user_id) %>
          <div class="pull-right">
            | <%= link_to edit_offer_demand_path(offer_demand) do %>
                <span class="glyphicon glyphicon-pencil"></span> upraviť
              <% end %>
            | <%= link_to offer_demand, method: :delete,
                          data: { confirm: 'Ste si istý?'} do %>
                  <span class="glyphicon glyphicon-trash"></span> zmazať
              <% end %>
          </div>
      <% end %>
    </div>
  </td>
  <td>
    <div class="price text-center"><%= price_format(offer_demand.price) %></div>
  </td>
  <td>
    <div class="price text-right"><%= rating_format(offer_demand.rating) %></div>
  </td>
</tr>
<% end %>

app/views/offer_demands/edit.html.erb
<% provide(:title, 'Upraviť ponuku') %>
<div class="well">
  <h1>Upraviť ponuku</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@offer_demand) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <%= f.label :názov %>
          <%= f.text_field :title, class: 'form-control' %>

          <%= f.label :popis %>
          <div class="field">
            <%= f.text_area :content, placeholder: 'Popis novej ponuky ...', class: 'form-control' %>
          </div>

          <%= f.label :Dátum %>
          <%= f.date_field :date %>

          <%= f.label :Typ %>
          <% options = options_from_collection_for_select(Type.all, 'id', 'name', @offer_demand.type_id) %>
          <%= f.select :type_id,  options %>

          <%= f.label 'Cena v eurách' %>
          <%= f.text_field :price, class: 'form-control' %>

          <%= f.label 'Viditeľnosť' %>
          <% options = options_for_select([['viditeľná', true], ['neviditeľná', false]], @offer_demand.visible) %>
          <%= f.select :visible,  options %>

          <%= f.label 'Pridať obrázok' %>
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>

          <%= f.submit 'Uložiť zmeny', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/offer_demands/new.html.erb
<% provide(:title, 'Nová ponuka') %>
<div class="well">
  <h1>Nová ponuka</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@offer_demand, html: { multipart: true }) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <%= f.label :názov do %>
              Názov<span class="red"> *</span>
          <% end %>
          <%= f.text_field :title, class: 'form-control' %>

          <%= f.label :popis do %>
              Popis<span class="red"> *</span>
          <% end %>
          <div class="field">
            <%= f.text_area :content, placeholder: 'Popis novej ponuky ...', class: 'form-control' %>
          </div>

          <%= f.label :Dátum %>
          <%= f.text_field :date, type: :date %>

          <%= f.label :Typ do %>
              Typ<span class="red"> *</span>
          <% end %>
          <% options = options_from_collection_for_select(Type.all, 'id', 'name') %>
          <%= f.select :type_id,  options %>

          <%= f.label :price do %>
              Cena v eurách<span class="red"> *</span>
          <% end %>
          <%= f.text_field :price, class: 'form-control' %>

          <%= f.label :visibility do %>
              Viditeľnosť ponuky pre ostatných<span class="red"> *</span>
          <% end %>
          <% options = options_for_select([['viditeľná', true], ['neviditeľná', false]]) %>
          <%= f.select :visible,  options %>

          <%= f.label 'Pridať obrázok' %>
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>

          <%= f.submit 'Vytvor novú ponuku', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
  <span class="red">*</span> povinné udaje označené hviezdičkou
</div>

<script type="text/javascript">
  $('#offer_demand_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/offer_demands/show.html.erb
<% provide(:title, @offer_demand.title) %>

<% if Rails.env.production? && flash[:success] == 'Nová ponuka vytvorená!' %>
    <script>
      <%= analytics_track_event 'Ponuka', 'Vytvorená' %>
    </script>
<% end %>

<div class="well">
  <div class="row offer">
    <h1><%= @offer_demand.title %></h1>
    <div class="col-xs-5 col-md-6">
      <% if @offer_demand.picture? %>
          <%= image_tag(@offer_demand.picture.url, alt: 'Offer picture', class: 'picture')%>
      <% else %>
          <% case @offer_demand.type_id %>
          <% when 1 %>
              <%= image_tag('offer.png', alt: 'offer logo', class: 'picture') %>
          <% when 2 %>
              <%= image_tag('service.png', alt: 'service logo', class: 'picture') %>
          <% when 3 %>
              <%= image_tag('demand.png', alt: 'demand logo', class: 'picture') %>
          <% when 4 %>
              <%= image_tag('event.png', alt: 'event logo', class: 'picture') %>
          <% when 5 %>
              <%= image_tag('other.png', alt: 'other logo', class: 'picture') %>
          <% end %>
      <% end %>
    </div>
    <div class="offer-info col-xs-6 col-xs-offset-1 col-md-5 col-md-offset-1">
      <h4>Popis:</h4>
      <p><%= @offer_demand.content %></p>
      <h4>Autor:</h4>
      <%= link_to User.find(@offer_demand.user_id).name, User.find(@offer_demand.user_id) %>
      <% unless @offer_demand.date.nil? %>
        <h4>Dátum:</h4>
        <p><%= @offer_demand.date.strftime('%-d.%-m %Y') %></p>
      <% end %>
      <h4>Typ:</h4>
      <p><%= @offer_demand.type_name %></p>
      <h4>Cena:</h4>
      <p><%= price_format(@offer_demand.price) %></p>
      <h4>Internát:</h4>
      <p><%= @offer_demand.dorm_name %></p>
      <h4>Región:</h4>
      <p><%= @offer_demand.region_name %></p>
      <h4>Priemerné hodnotenie z komentárov:</h4>
      <p><%= rating_format(@offer_demand.rating) %></p>
    </div>
    <% if current_user?User.find(@offer_demand.user_id) %>
        <div class="control-panel">
          <%= link_to edit_offer_demand_path(@offer_demand), class: 'btn btn-lg btn-primary' do %>
              <span class="glyphicon glyphicon-pencil"></span> Upraviť ponuku
          <% end %>
          <%= link_to @offer_demand, method: :delete,
                        data: { confirm: 'Ste si istý?'}, class: 'btn btn-lg btn-primary' do %>
              <span class="glyphicon glyphicon-trash"></span> Zmazať ponuku
          <% end %>
        </div>
    <% end %>
  </div>
</div>
<% if @offer_demand.comments.any? %>
    <div class="well">
    <%= will_paginate @comments %>
      <h3>Komentáre (<%= @offer_demand.comments.count %>)</h3>
      <ol class="comments">
        <%= render @comments %>
      </ol>
    </div>
<% end %>

<% if logged_in? %>
    <div class="well">
      <div class="row">
      <aside class="col-md-6 col-md-offset-3">
        <section class="comment_form">
          <%= render 'shared/comment_form' %>
        </section>
      </aside>
    </div>
  </div>
<% end %>