config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :offer_demands,       only: [:new, :create, :edit, :update, :destroy, :show]
  resources :comments,            only: [:create, :destroy]
  resources :dorms,               only: [:show]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'od studentov pre studentov', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href=<%= root_path %>>
            <div class="glyphicon glyphicon-home"></div> Domov
          </a>
        </li>
        <li>
          <a href=<%= about_path %>>
            <div class="glyphicon glyphicon-info-sign"></div> O stránke
          </a>
        </li>
        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <b class="glyphicon glyphicon-user"></b> Účet <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to new_offer_demand_path do %>
                      <span class="glyphicon glyphicon-plus"></span> Nová ponuka
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to user_path(current_user) do %>
                      <span class="glyphicon glyphicon-th-list"></span> Profil a ponuky
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to edit_user_path(current_user) do %>
                    <span class="glyphicon glyphicon-cog"></span> Zmeniť profil
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to logout_path, method: :delete do %>
                    <div class="glyphicon glyphicon-log-out"></div> Odhlásiť sa
                  <% end %>
                </li>
              </ul>
            </li>
        <% else %>
            <li>
              <%= link_to login_path do %>
                <div class="glyphicon glyphicon-log-in"></div> Prihlásiť sa
              <% end %>
            </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
  <ul class="nav sidebar-nav">
    <li class="sidebar-brand">
      <h3>Internáty</h3>
    </li>
    <% last = '' %>
    <% @dorm_with_region.each do |dorm| %>
        <% if last == '' %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><div class="glyphicon glyphicon-home"></div> <%= dorm.region.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href=<%= dorm_path(dorm.id) %>><%= dorm.name %> </a></li>
        <% elsif last != dorm.region.name %>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><div class="glyphicon glyphicon-home"></div> <%= dorm.region.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href=<%= dorm_path(dorm.id) %>><%= dorm.name %> </a></li>
        <% else %>
            <li><a href=<%= dorm_path(dorm.id) %>><%= dorm.name %> </a></li>
        <% end %>
        <% last = dorm.region.name %>
    <% end %>
    </ul>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= analytics_init if GoogleAnalytics.valid_tracker? %>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="wrapper" class="active">
      <div id="overlay"></div>
        <%= render 'layouts/sidebar' %>
      <div id="page-content-wrapper">
        <h1 id="button-dorms">
          <a data-toggle="offcanvas" href="#">
            <span class="glyphicon glyphicon-home home"></span>
            <div class="pull-right">Internáty</div>
          </a>
        </h1>
        <div class="container">
          <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
          <%= debug(params) if Rails.env.development? %>
        </div>
      </div>
    </div>
  </body>
</html>